In [9]:
 #自动求导
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [10]:
x.requires_grad_(True)
x.grad

In [11]:
y = 2 * torch.dot(x ,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [12]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [13]:
x.grad == 4 * x

tensor([True, True, True, True])

In [15]:
#默认情况下pytorch会累计梯度，要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [16]:
#深度学习中不是计算微分矩阵，而是计算批量中每个样本单独计算的偏导数之和
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [17]:
#将某些计算移动到记录的计算图之外
x.grad.zero_()
y = x * x 
u = y.detach()      #u不再是x的函数，而是一个常数，它的值等于x*x
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [18]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [22]:
#即使构建的函数计算图需要通过python的控制流（条件，循环或任意函数的调用），仍然可以求导得到梯度
def  f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum()>0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()
a.grad == d / a

tensor(True)

### 线性回归